<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns="http://xmlns.darwin-it.nl/xsd/adapter/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://platform.integration.oracle/blocks/adapter/fw/metadata"
                exclude-result-prefixes="oracle-xsl-mapper xsi xsd xsl ns0 tns oraxsl"
                xmlns:tns="http://xmlns.darwin-it.nl/xsd/adapter/metadata">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../xsd/jcaAdapter.xsd"/>
        <oracle-xsl-mapper:rootElement name="adapter-config"
                                       namespace="http://platform.integration.oracle/blocks/adapter/fw/metadata"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../xsd/jcaAdapterProps.xsd"/>
        <oracle-xsl-mapper:rootElement name="adapter-config"
                                       namespace="http://xmlns.darwin-it.nl/xsd/adapter/metadata"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 180705.1130.0048) AT [TUE NOV 27 14:03:09 CET 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <adapter-config name="{/ns0:adapter-config/@name}" adapter="{/ns0:adapter-config/@adapter}"
                    wsdlLocation="{/ns0:adapter-config/@wsdlLocation}">
      <connection-factory location="{/ns0:adapter-config/ns0:connection-factory/@location}"
                          adapterRef="{/ns0:adapter-config/ns0:connection-factory/@adapterRef}"/>
      <xsl:choose>
        <xsl:when test="/ns0:adapter-config/ns0:endpoint-interaction">
          <endpoint portType="{/ns0:adapter-config/ns0:endpoint-interaction/@portType}"
                    operation="{/ns0:adapter-config/ns0:endpoint-interaction/@operation}">
            <spec className="{/ns0:adapter-config/ns0:endpoint-interaction/ns0:interaction-spec/@className}"
                  type="interaction">
              <DestinationName>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-interaction/ns0:interaction-spec/ns0:property[@name='DestinationName']/@value"/>
              </DestinationName>
              <DeliveryMode>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-interaction/ns0:interaction-spec/ns0:property[@name='DeliveryMode']/@value"/>
              </DeliveryMode>
              <TimeToLive>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-interaction/ns0:interaction-spec/ns0:property[@name='TimeToLive']/@value"/>
              </TimeToLive>
              <UseMessageListener/>
              <MessageSelector/>
              <PayloadType>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-interaction/ns0:interaction-spec/ns0:property[@name='PayloadType']/@value"/>
              </PayloadType>
              <QueueName>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-interaction/ns0:interaction-spec/ns0:property[@name='QueueName']/@value"/>
              </QueueName>
              <ObjectFieldName>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-interaction/ns0:interaction-spec/ns0:property[@name='ObjectFieldName']/@value"/>
              </ObjectFieldName>
              <PayloadHeaderRequired>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-interaction/ns0:interaction-spec/ns0:property[@name='PayloadHeaderRequired']/@value"/>
              </PayloadHeaderRequired>
              <RecipientList>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-interaction/ns0:interaction-spec/ns0:property[@name='RecipientList']/@value"/>
              </RecipientList>
              <Consumer/>
            </spec>
          </endpoint>
        </xsl:when>
        <xsl:when test="/ns0:adapter-config/ns0:endpoint-activation">
          <endpoint portType="{/ns0:adapter-config/ns0:endpoint-activation/@portType}"
                    operation="{/ns0:adapter-config/ns0:endpoint-activation/@operation}">
            <spec className="{/ns0:adapter-config/ns0:endpoint-activation/ns0:activation-spec/@className}"
                  type="activation">
              <DestinationName>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-activation/ns0:activation-spec/ns0:property[@name='DestinationName']/@value"/>
              </DestinationName>
              <DeliveryMode/>
              <TimeToLive/>
              <UseMessageListener>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-activation/ns0:activation-spec/ns0:property[@name='UseMessageListener']/@value"/>
              </UseMessageListener>
              <MessageSelector>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-activation/ns0:activation-spec/ns0:property[@name='MessageSelector']/@value"/>
              </MessageSelector>
              <PayloadType>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-activation/ns0:activation-spec/ns0:property[@name='PayloadType']/@value"/>
              </PayloadType>
              <QueueName>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-activation/ns0:activation-spec/ns0:property[@name='QueueName']/@value"/>
              </QueueName>
              <ObjectFieldName>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-activation/ns0:activation-spec/ns0:property[@name='ObjectFieldName']/@value"/>
              </ObjectFieldName>
              <PayloadHeaderRequired>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-activation/ns0:activation-spec/ns0:property[@name='PayloadHeaderRequired']/@value"/>
              </PayloadHeaderRequired>
              <RecipientList/>
              <Consumer>
                <xsl:value-of select="/ns0:adapter-config/ns0:endpoint-activation/ns0:activation-spec/ns0:property[@name='Consumer']/@value"/>
              </Consumer>
            </spec>
          </endpoint>
        </xsl:when>
      </xsl:choose>
    </adapter-config>
  </xsl:template>
</xsl:stylesheet>
