@set JAVA_HOME="c:\PROGRA~1\Java\JDK18~1.0_1"
@set ORACLE_HOME=c:\Oracle\product\ohs12.2.1.3
@set IDENTITY_STORE=20180312-identity-ohs.jks 
@set IDENTITY_STORE_P12=20180312-identity-ohs.p12
@set IDENTITY_CSR=20180312-identity-ohs.csr
@set IDENTITY_CERT=tomcat_test_Darwin_nl.crt
@set IDENTITY_PASS=9KElad932ae2Xka3OpOQ
@set IDENTITY_ALIAS=ohs
@set KEY_PASS=9KElad932ae2Xka3OpOQ
@set TRUST_STORE=20180312-trust-ohs.jks 
@set TRUST_PASS=9KElad932ae2Xka3OpOQ
@set DNAME="CN=ohs.darwin-it.nl, OU=Professionals, O=Darwin-IT, L=Amersfoort, ST=Utrecht, C=NL, EmailAddress=friemele.frans@darwin-it.nl"
@set SAN=dns:ohs,dns:ohs.darwin-it.local,dns:ohs,dns:ohs.darwin-it.nl,dns:ohs.darwin-it.nl,dns:ohs
@set VALIDITY=365
@set KEYSIZE=2048
@set CERT_HOME="certificaat"
@set ROOT_CERT_HOME="certificaat\Root Certificates"
@set ROOT_CERT_1=AddTrustExternalCARoot.crt
@set ROOT_CERT_ALIAS_1=AddTrustExternalCARoot
@set ROOT_CERT_2=COMODORSAAddTrustCA.crt
@set ROOT_CERT_ALIAS_2=COMODORSAAddTrustCA
@set ROOT_CERT_3=COMODORSADomainValidationSecureServerCA.crt
@set ROOT_CERT_ALIAS_3=COMODORSADomainValidationSecureServerCA