<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.oracle.com/bpel/sensor"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.darwin-it.nl/bpel/sensorActions"
                exclude-result-prefixes="oracle-xsl-mapper xsi xsd xsl ns0 tns oraxsl">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../xsd/sensorActions.xsd"/>
        <oracle-xsl-mapper:rootElement name="actions" namespace="http://xmlns.oracle.com/bpel/sensor"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../xsd/sensorActionsProps.xsd"/>
        <oracle-xsl-mapper:rootElement name="sensors" namespace="http://xmlns.darwin-it.nl/bpel/sensorActions"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 180705.1130.0048) AT [WED JAN 15 13:23:12 CET 2020].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <sensors>
      <xsl:for-each select="/ns0:actions/ns0:action/ns0:sensorName">
        <xsl:element name="{.}">
          <actionName>
            <xsl:value-of select="../@name"/>
          </actionName>
          <action name="{../@name}">
            <xsl:if test="../@publishName">
              <xsl:attribute name="publishName">
                <xsl:value-of select="../@publishName"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="../@publishType">
              <xsl:attribute name="publishType">
                <xsl:value-of select="../@publishType"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="../@enabled">
              <xsl:attribute name="enabled">
                <xsl:value-of select="../@enabled"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="../@filter">
              <xsl:attribute name="filter">
                <xsl:value-of select="../@filter"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="../@publishTarget">
              <xsl:attribute name="publishTarget">
                <xsl:value-of select="../@publishTarget"/>
              </xsl:attribute>
            </xsl:if>
            <property>
              <xsl:if test="../ns0:property/@name">
                <xsl:attribute name="name">
                  <xsl:value-of select="../ns0:property/@name"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="../ns0:property"/>
            </property>
          </action>
        </xsl:element>
      </xsl:for-each>
    </sensors>
  </xsl:template>
</xsl:stylesheet>
